name: chromosight
channels:
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asciitree=0.3.3=py_2
  - attrs=22.1.0=py37h06a4308_0
  - bcftools=1.3.1=h5bf99c6_7
  - biopython=1.78=py37h7f8727e_0
  - blas=1.0=mkl
  - bokeh=2.4.3=py37h06a4308_0
  - bottleneck=1.3.5=py37h7deecbd_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - chromosight=1.6.3=pyhdfd78af_0
  - click=8.0.4=py37h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cooler=0.9.3=pyhdfd78af_0
  - curl=7.88.1=h37d81fd_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py37h5eee18b_0
  - dask=2021.10.0=pyhd3eb1b0_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dill=0.3.6=py37h06a4308_0
  - distributed=2021.10.0=py37h06a4308_0
  - docopt=0.6.2=py37h06a4308_1
  - fftw=3.3.9=h5eee18b_2
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2022.11.0=py37h06a4308_0
  - giflib=5.2.2=h5eee18b_0
  - h5py=3.7.0=py37h737f45e_0
  - hdf5=1.10.6=h3ffc7dd_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - htslib=1.3.1=hc8ab001_4
  - importlib-metadata=4.11.3=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=py37h06a4308_0
  - joblib=1.1.1=py37h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsonschema=4.17.3=py37h06a4308_0
  - kiwisolver=1.4.4=py37h6a678d5_0
  - krb5=1.20.1=h568e23c_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=7.88.1=h91b91d3_2
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - locket=1.0.0=py37h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.1=py37h7f8727e_0
  - matplotlib-base=3.5.3=py37hf590b9c_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - msgpack-python=1.0.3=py37hd09550d_0
  - multiprocess=0.70.14=py37h06a4308_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.4=py37he184ba9_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openssl=1.1.1w=h7f8727e_0
  - packaging=22.0=py37h06a4308_0
  - pairix=0.3.7=py37h84994c4_0
  - pandas=1.3.5=py37h8c16a72_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pillow=9.4.0=py37h6a678d5_0
  - pip=22.3.1=py37h06a4308_0
  - pkgutil-resolve-name=1.3.10=py37h06a4308_0
  - psutil=5.9.0=py37h5eee18b_0
  - pyfaidx=0.8.1.3=pyhdfd78af_0
  - pyparsing=3.0.9=py37h06a4308_0
  - pyrsistent=0.18.0=py37heee7806_0
  - pysam=0.9.1=py37h7a788bc_7
  - python=3.7.16=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2022.7=py37h06a4308_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - pyyaml=6.0=py37h5eee18b_1
  - readline=8.2=h5eee18b_0
  - samtools=1.3.1=h1b8c3c0_8
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37h6c91a56_2
  - setuptools=65.6.3=py37h06a4308_0
  - simplejson=3.17.6=py37h7f8727e_0
  - six=1.16.0=pyhd3eb1b0_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.45.3=h5eee18b_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.14=h39e8969_0
  - toolz=0.12.0=py37h06a4308_0
  - tornado=6.2=py37h5eee18b_0
  - typing_extensions=4.4.0=py37h06a4308_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zict=2.1.0=py37h06a4308_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
prefix: /home/apiazza/miniconda3/envs/chromosight
