name: cooltools071
channels:
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=hac33072_0
  - asciitree=0.3.3=py_2
  - aws-c-auth=0.9.0=h0fbd49f_19
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.5=h149bd38_3
  - aws-c-http=0.10.4=h37a7233_0
  - aws-c-io=0.21.2=h6252d9a_1
  - aws-c-mqtt=0.13.3=h19deb91_3
  - aws-c-s3=0.8.6=h800fcd2_2
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.33.1=hb4fd278_2
  - aws-sdk-cpp=1.11.606=h31ade35_1
  - azure-core-cpp=1.16.0=h3a458e0_0
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=h4bb41a7_3
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - bioframe=0.8.0=pyhdfd78af_0
  - biopython=1.85=py312h4c3975b_2
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.8.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py312h1289d80_4
  - brunsli=0.1=he3183e4_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.21.2=h4cfbee9_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h35888ee_1
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - contourpy=1.3.3=py312hd9148b4_2
  - cooler=0.10.4=pyhdfd78af_0
  - cooltools=0.7.1=py312hc9302aa_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py312h66e93f0_0
  - dask=2025.7.0=pyhe01879c_0
  - dask-core=2025.7.0=pyhe01879c_1
  - dav1d=1.2.1=hd590300_0
  - dill=0.4.0=pyhd8ed1ab_0
  - distributed=2025.7.0=pyhe01879c_0
  - fonttools=4.59.2=py312h8a5da7c_0
  - freetype=2.14.0=ha770c72_1
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.14.0=nompi_py312ha4f8f14_101
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.22.1=h566b1c6_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2025.8.2=py312h4ecb025_4
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_1
  - krb5=1.21.3=h659f571_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=21.0.0=hb708d0b_3_cpu
  - libarrow-acero=21.0.0=h635bf11_3_cpu
  - libarrow-compute=21.0.0=h8c2c5c3_3_cpu
  - libarrow-dataset=21.0.0=h635bf11_3_cpu
  - libarrow-substrait=21.0.0=h3f74fd7_3_cpu
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=35_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.0=ha770c72_1
  - libfreetype6=2.14.0=h73754d4_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_5
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h1e535eb_0
  - libhwy=1.3.0=h4c17acf_0
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h6cb5226_4
  - liblapack=3.9.0=35_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopenssl-static=3.5.2=hb03c661_0
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=21.0.0=h790f06f_3_cpu
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h9ef548d_1
  - libre2-11=2025.08.12=h7b12aa8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.0=h8261f1e_6
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.1=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.14.6=h26afc86_2
  - libxml2-16=2.14.6=ha9997c6_2
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvmlite=0.44.0=py312he100287_2
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py312h5d89b6d_1
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib-base=3.10.6=py312he3d6523_1
  - msgpack-python=1.1.1=py312hd9148b4_1
  - multiprocess=0.70.18=py312h5253ce2_1
  - munkres=1.0.7=py_1
  - mysql-connector-c=6.1.11=h659d440_1008
  - narwhals=2.5.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h3f2d84a_0
  - numba=0.61.2=py312h7bcfee6_1
  - numpy=1.26.4=py312heda63a1_0
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.5.2=h26f9b46_0
  - orc=2.2.0=h1bc01a4_0
  - packaging=25.0=pyh29332c3_1
  - pairix=0.3.9=py312h4711d71_0
  - pandas=2.3.2=py312hf79963d_0
  - partd=1.4.2=pyhd8ed1ab_0
  - perl=5.32.1=7_hd590300_perl5
  - pillow=11.3.0=py312h0e488c8_1
  - pip=25.2=pyh8b19718_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - psutil=7.0.0=py312h4c3975b_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=21.0.0=py312h7900ff3_0
  - pyarrow-core=21.0.0=py312hc195796_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pyfaidx=0.9.0.3=pyhdfd78af_0
  - pyparsing=3.2.4=pyhcf101f3_0
  - pysam=0.23.3=py312h47d5410_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyvcf3=1.0.4=py312h0fa9677_0
  - pywavelets=1.9.0=py312h4f23490_1
  - pyyaml=6.0.2=py312h178313f_2
  - qhull=2020.2=h434a139_5
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.08.12=h5301d42_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - s2n=1.5.23=h8e187f5_0
  - samtools=1.22.1=h96c455f_0
  - scikit-image=0.25.2=py312hf79963d_2
  - scikit-learn=1.7.2=py312h4f0b9e3_0
  - scipy=1.16.2=py312h7a1785b_0
  - setuptools=80.9.0=pyhff2d567_0
  - simplejson=3.20.1=py312h4c3975b_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - svt-av1=3.1.2=hecca717_0
  - tblib=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.9.9=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.2=py312h4c3975b_1
  - tzdata=2025b=h78e105d_0
  - ucsc-bedgraphtobigwig=482=hdc0a859_0
  - unicodedata2=16.0.0=py312h4c3975b_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zfp=1.0.1=h909a3a2_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py312h5253ce2_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/apiazza/miniconda3/envs/cooltools071
