name: sshicstuff18
channels:
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - asciitree=0.3.3=py_2
  - aws-c-auth=0.8.0=hb921021_15
  - aws-c-cal=0.8.1=h1a47875_3
  - aws-c-common=0.10.6=hb9d3cd8_0
  - aws-c-compression=0.3.0=h4e1184b_5
  - aws-c-event-stream=0.5.0=h7959bf6_11
  - aws-c-http=0.9.2=hefd7a92_4
  - aws-c-io=0.15.3=h173a860_6
  - aws-c-mqtt=0.11.0=h11f4f37_12
  - aws-c-s3=0.7.7=hf454442_0
  - aws-c-sdkutils=0.2.1=h4e1184b_4
  - aws-checksums=0.2.2=h4e1184b_4
  - aws-crt-cpp=0.29.7=hd92328a_7
  - aws-sdk-cpp=1.11.458=hc430e4a_4
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - bioframe=0.7.2=pyhdfd78af_0
  - blas=1.0=openblas
  - bokeh=3.6.2=py312h06a4308_0
  - bottleneck=1.4.2=py312ha883a20_0
  - bowtie2=2.5.4=he96a11b_5
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cached-property=1.5.2=py_0
  - certifi=2025.1.31=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py312h06a4308_0
  - cloudpickle=3.0.0=py312h06a4308_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cooler=0.10.3=pyhdfd78af_0
  - coreutils=9.5=h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=1.0.1=py312h5eee18b_0
  - dask=2025.2.0=py312h06a4308_0
  - dask-core=2025.2.0=py312h06a4308_0
  - dask-expr=2.0.0=py312h06a4308_0
  - dill=0.3.8=py312h06a4308_0
  - distributed=2025.2.0=py312h06a4308_0
  - fonttools=4.55.3=py312h5eee18b_0
  - freetype=2.13.3=h48d6fc4_0
  - fsspec=2024.12.0=py312h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.7.1=hbabe93e_0
  - h5py=3.13.0=nompi_py312hedeef09_100
  - hdf5=1.14.3=nompi_h2d575fe_109
  - heapdict=1.0.1=pyhd3eb1b0_0
  - htslib=1.21=h566b1c6_1
  - icu=75.1=he02047a_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.5.0=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - k8=1.2=h6618dc6_3
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - kiwisolver=1.4.8=py312h6a678d5_0
  - krb5=1.21.3=h143b758_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h6a678d5_0
  - libarrow=18.1.0=h3b07799_4_cpu
  - libarrow-acero=18.1.0=h8bbc2ab_4_cpu
  - libarrow-dataset=18.1.0=h8bbc2ab_4_cpu
  - libarrow-substrait=18.1.0=had74209_4_cpu
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcrc32c=1.1.2=h6a678d5_0
  - libcurl=8.12.1=h332b0f4_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libgoogle-cloud=2.31.0=h804f50b_0
  - libgoogle-cloud-storage=2.31.0=h0121fbd_0
  - libgrpc=1.67.1=hc2c308b_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblzma=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libparquet=18.1.0=hf4f6db6_4_cpu
  - libpng=1.6.47=h943b412_0
  - libprotobuf=5.28.2=h5b01275_0
  - libre2-11=2024.07.02=hbbce691_2
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hc4654cb_2
  - libutf8proc=2.9.0=hb9d3cd8_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.6=h8d12d68_0
  - libzlib=1.3.1=hb9d3cd8_2
  - locket=1.0.0=py312h06a4308_0
  - lz4=4.3.2=py312h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - minimap2=2.28=h577a1d6_4
  - msgpack-python=1.0.3=py312hdb19cb5_0
  - multiprocess=0.70.15=py312h06a4308_0
  - ncurses=6.5=h2d0b736_3
  - numexpr=2.10.1=py312hd28fd6d_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.4.1=h7b32b05_0
  - orc=2.0.3=he039a57_0
  - packaging=24.2=py312h06a4308_0
  - pairix=0.3.9=py312h4711d71_0
  - pairtools=1.1.0=py312h5219090_3
  - pandas=2.2.3=py312h6a678d5_0
  - partd=1.4.2=py312h06a4308_0
  - pbgzip=2016.08.04=hb1d24b7_6
  - perl=5.38.2=0_h5eee18b_perl5
  - pillow=11.1.0=py312h80c1187_0
  - pip=25.0=py312h06a4308_0
  - psutil=5.9.0=py312h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=18.1.0=py312h7900ff3_0
  - pyarrow-core=18.1.0=py312h01725c0_0_cpu
  - pyfaidx=0.8.1.3=pyhdfd78af_0
  - pyparsing=3.2.0=py312h06a4308_0
  - pyproject_hooks=1.0.0=py312h06a4308_0
  - pysam=0.22.1=py312h47d5410_3
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.9=h9e4cc4f_1_cpython
  - python-build=1.2.2.post1=py312h06a4308_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-lmdb=1.6.2=py312h6a678d5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=py312h06a4308_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - s2n=1.5.11=h072c03f_0
  - samtools=1.21=h96c455f_1
  - scipy=1.15.1=py312h2809609_0
  - seqtk=1.4=h577a1d6_3
  - simplejson=3.19.2=py312h5eee18b_1
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tblib=1.7.0=pyhd3eb1b0_0
  - tk=8.6.13=noxft_h4845f30_101
  - toolz=1.0.0=py312h06a4308_0
  - tornado=6.4.2=py312h5eee18b_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_1
  - urllib3=2.3.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2022.9.0=py312h06a4308_1
  - yaml=0.2.5=h7b6447c_0
  - zict=3.0.0=py312h06a4308_0
  - zipp=3.21.0=py312h06a4308_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - biopython==1.83
      - blinker==1.9.0
      - cython==3.0.12
      - dash==2.17.1
      - dash-bootstrap-components==1.6.0
      - dash-core-components==2.0.0
      - dash-daq==0.5.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - docopt==0.6.2
      - flask==3.0.3
      - hicstuff==3.2.4
      - iniconfig==2.1.0
      - itsdangerous==2.2.0
      - joblib==1.4.2
      - kaleido==0.2.1
      - matplotlib==3.9.4
      - nest-asyncio==1.6.0
      - parasplit==1.1.5
      - plotly==5.24.0
      - pluggy==1.5.0
      - pyfastx==2.1.0
      - pytest==8.3.5
      - retrying==1.3.4
      - scikit-learn==1.6.1
      - setuptools==75.1.0
      - sshicstuff==1.15.0
      - stringcase==1.2.0
      - tenacity==9.0.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.12.2
      - werkzeug==3.0.6
prefix: /home/apiazza/miniconda3/envs/sshicstuff18
