name: jupyter-python3.7
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.5.0=py37h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h7f8727e_0
  - asciitree=0.3.3=py_2
  - attrs=22.1.0=py37h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcftools=1.3.1=h5bf99c6_7
  - beautifulsoup4=4.11.1=py37h06a4308_0
  - bioframe=0.8.0=pyhdfd78af_0
  - biopython=1.78=py37h7f8727e_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=2.4.3=py37h06a4308_0
  - bottleneck=1.3.5=py37h7deecbd_0
  - bowtie2=2.3.5.1=py37he513fc3_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotlipy=0.7.0=py37h27cfd23_1003
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py37h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cooler=0.9.3=pyhdfd78af_0
  - cooltools=0.5.1=py37h37892f8_1
  - cryptography=38.0.2=py37h5994e8b_1
  - curl=7.88.1=hdc1c0ab_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.10.1=py37h516909a_0
  - dask=2022.2.0=pyhd8ed1ab_0
  - dask-core=2022.2.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.6=py37h06a4308_0
  - distributed=2022.2.0=py37h89c1867_0
  - docopt=0.6.2=py37h06a4308_1
  - entrypoints=0.4=py37h06a4308_0
  - fftw=3.3.9=h5eee18b_2
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2022.11.0=py37h06a4308_0
  - giflib=5.2.2=h5eee18b_0
  - h5py=3.7.0=py37h737f45e_0
  - hdf5=1.10.6=h3ffc7dd_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - hicstuff=3.1.2=pyhdfd78af_0
  - htslib=1.3.1=h0cf4675_7
  - idna=3.4=py37h06a4308_0
  - imagecodecs-lite=2019.12.3=py37hc105733_5
  - imageio=2.36.0=pyh12aca89_1
  - importlib-metadata=4.11.3=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.2=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py37h06a4308_1
  - jinja2=3.1.2=py37h06a4308_0
  - joblib=1.1.1=py37h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsonschema=4.17.3=py37h06a4308_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.11.2=py37h06a4308_0
  - jupyter_server=1.23.4=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - k8=0.2.5=h9a82719_1
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.4=py37h6a678d5_0
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=7.88.1=hdc1c0ab_1
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.1.0=h767d61c_5
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libtiff=4.5.1=hffd6297_1
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.36.0=py37h9d7f4d0_0
  - locket=1.0.0=py37h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.1=py37h7f8727e_0
  - matplotlib-base=3.5.3=py37hf590b9c_0
  - matplotlib-inline=0.1.6=py37h06a4308_0
  - minimap2=2.22=h5bf99c6_0
  - mistune=2.0.4=py37h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - msgpack-python=1.0.3=py37hd09550d_0
  - multiprocess=0.70.14=py37h06a4308_0
  - munkres=1.0.7=py_1
  - nbclassic=0.5.2=py37h06a4308_0
  - nbclient=0.5.13=py37h06a4308_0
  - nbconvert=7.6.0=pyhd8ed1ab_0
  - nbconvert-core=7.6.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.6.0=pyhd8ed1ab_0
  - nbformat=5.7.0=py37h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py37h06a4308_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - notebook=6.5.7=pyha770c72_0
  - notebook-shim=0.2.2=py37h06a4308_0
  - numba=0.53.1=py37ha9443f7_0
  - numexpr=2.8.4=py37he184ba9_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openssl=3.5.2=h26f9b46_0
  - packaging=22.0=py37h06a4308_0
  - pairix=0.3.7=py37h190e900_3
  - pandas=1.3.5=py37h8c16a72_0
  - pandoc=3.6.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - patsy=0.5.3=py37h06a4308_0
  - perl=5.38.2=0_h5eee18b_perl5
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py37h6a678d5_0
  - pip=22.3.1=py37h06a4308_0
  - pkgutil-resolve-name=1.3.10=py37h06a4308_0
  - prometheus_client=0.14.1=py37h06a4308_0
  - prompt-toolkit=3.0.36=py37h06a4308_0
  - psutil=5.9.0=py37h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pyfaidx=0.8.1.3=pyhdfd78af_0
  - pyfastx=0.6.7=py37hed695b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pyparsing=3.0.9=py37h06a4308_0
  - pyrsistent=0.18.0=py37heee7806_0
  - pysam=0.9.1=py37h7a788bc_7
  - pysocks=1.7.1=py37_1
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py37h06a4308_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.7=py37h06a4308_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - pywavelets=1.3.0=py37hda87dfa_1
  - pyyaml=6.0=py37h5eee18b_1
  - pyzmq=23.2.0=py37h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py37h06a4308_0
  - samtools=1.3.1=h0cf4675_11
  - scikit-image=0.19.3=py37hfb7772e_1
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37h6c91a56_2
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=59.8.0=py37h89c1867_1
  - simplejson=3.17.6=py37h7f8727e_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py37h06a4308_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.2.post1=py37h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - statsmodels=0.13.5=py37h7deecbd_1
  - tbb=2020.3=hfd86e86_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.17.1=py37h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2020.6.3=py_0
  - tinycss2=1.2.1=py37h06a4308_0
  - tk=8.6.14=h39e8969_0
  - toolz=0.12.0=py37h06a4308_0
  - tornado=6.1=py37h540881e_3
  - traitlets=5.7.1=py37h06a4308_0
  - typing-extensions=4.4.0=py37h06a4308_0
  - typing_extensions=4.4.0=py37h06a4308_0
  - urllib3=1.26.14=py37h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37h06a4308_4
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zict=2.1.0=py37h06a4308_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - serpentine==0.1.3
prefix: /home/apiazza/miniconda3/envs/jupyter-python3.7
